### ISSUE TITLE
Ignore path do not work with strategy

### ISSUE THREAD

**Issue by daixiang0** [fkirc/skip-duplicate-actions#118]
Details see https://github.com/dapr/dapr/pull/3267, tests skip while github wait for its report.

**Comment by daixiang0** [comment]
ping @fkirc

**Comment by fkirc** [comment]
Hi, I see something like the following output:

Run fkirc/skip-duplicate-actions@v3.4.0
  with:
    paths: ["**.md", ".codecov.yaml", ".github/**.yml"]
    github_token: ***
    paths_ignore: []
    cancel_others: false
    skip_after_successful_duplicate: true
    do_not_skip: ["workflow_dispatch", "schedule"]
    concurrent_skipping: never
Commit https://github.com/dapr/dapr/commit/97d7d775b4f0c7a98a65d9189321d7a719dcb851 is path-skipped: None of 'pkg/retry/retry.go' matches against patterns '**.md,.codecov.yaml,.github/**.yml'
Skip execution because all changes since https://github.com/dapr/dapr/actions/runs/920284926 are in ignored or skipped paths

In this case, it does not skip because retry.go does not match against the path. But please feel free to comment the exact output if this is wrong.

**Comment by daixiang0** [comment]
Could you see the whole github check, it hungs since wait for skipped tests's report.

**Comment by fkirc** [comment]
I will probably need an exact link to the workflow-run, instead of a link to th PR.

**Comment by daixiang0** [comment]
See https://github.com/dapr/dapr/pull/3267/checks?check_run_id=2780533631 please.

**Comment by fkirc** [comment]
Well, my guess is that you need to configure `paths_ignore` instead of `paths`.
`paths_ignore` is intended to skip things like documentation-changes or upload of test-reports.

**Comment by daixiang0** [comment]
I changed, seems it could not skip, see https://github.com/dapr/dapr/pull/3267/checks?check_run_id=2780688333

**Comment by fkirc** [comment]
Alright, so let's look at this output:

Run fkirc/skip-duplicate-actions@v3.4.0
  with:
    paths_ignore: ["**.md", ".codecov.yaml", ".github/**.yml"]
    github_token: ***
    paths: []
    cancel_others: false
    skip_after_successful_duplicate: true
    do_not_skip: ["workflow_dispatch", "schedule"]
    concurrent_skipping: never
Stop backtracking at commit https://github.com/dapr/dapr/commit/3942efd88e39860f45cc66ea275adffe05343222 because '.github/workflows/dapr-e2e-apps.yml,.github/workflows/dapr.yml,.github/workflows/kind-e2e.yaml' are not skippable against paths '' or paths_ignore '**.md,.codecov.yaml,.github/**.yml'
Do not skip execution because we did not find a transferable run

In this case, `github/workflows/kind-e2e.yaml` seems to _not_ match against any ignore-pattern.
One more note: I would recommend to not skip all those Action-yamls, because skipping Action-yamls might make it harder to change the Actions later on.

**Comment by daixiang0** [comment]
My config is ".github/**.yml", I assume it match all `yml` under ".github", is it not correct? How to fix it? Please help me.

**Comment by fkirc** [comment]
kind-e2e.yaml is a "yaml"-file, but not a "yml"-file.

**Comment by daixiang0** [comment]
Oh, I see.

Please see https://github.com/dapr/dapr/pull/3267/checks?check_run_id=2780688510, it skip tests, while github still wait for its report.

**Comment by daixiang0** [comment]
@fkirc 

Now it still can not fix this case:
> Consequently, GitHub's paths-ignore does not work for required checks. If you path-ignore a required check, then pull requests will block forever without being mergeable.

**Comment by daixiang0** [comment]
@fkirc could you help take a look?

**Comment by fkirc** [comment]
I guess that the remaining "bug" is about blocking PRs.
Not sure how to fix it, but there exist other issues in this repo that mention "matrix testing".

**Comment by daixiang0** [comment]
Do you mean https://github.com/fkirc/skip-duplicate-actions/issues/56?

**Comment by fkirc** [comment]
Yes, #56 is one of those issues.
I am pretty sure that the problem is solvable, but it might require some boilerplate code.

**Comment by daixiang0** [comment]
please help me solve this, thanks a lot!

**Comment by daixiang0** [comment]
@fkirc hi, why those files changed? Are they in cache?

See https://github.com/dapr/dapr/pull/3267/checks?check_run_id=2826627110

**Comment by daixiang0** [comment]
@fkirc why it test other commits outside? See https://github.com/dapr/dapr/pull/3267/checks?check_run_id=2827069911.

**Comment by fkirc** [comment]
I am not sure whether I understand the question, but I would recommend to look at index.ts within this repo.
