### ISSUE TITLE
Feature request: Skip duplicate action run based on trigger type

### ISSUE THREAD

**Issue by icopp** [fkirc/skip-duplicate-actions#34]
Given this setup:

```
on:
  push:
  pull_request:
```

...I'd really like functionality to always skip the `push`-triggered jobs when pushing to a branch that has a pull request open, in favor of the `pull request`-triggered jobs.

**Comment by fkirc** [comment]
The `skip-concurrent`-feature is already doing something similar, except that it is a race condition which job is skipped. If you do not really care which job is skipped, then the current version of this Action is already sufficient.
Therefore, can you elaborate on why the specific trigger is important for your use case?

With regard to implementation:
Currently, this Action only looks at "older" workflow-runs (workflow-runs that are older than the current workflow-run).
To implement your feature request, we would need to look at "younger" workflow-runs.
To make this safe, we would need a new set of rules to enforce that only one of two concurrent workflow-runs is allowed to skip.
An implementation might look as follows:

- Add a new optional input `skip_concurrent_trigger`. In your case, set `skip_concurrent_trigger` to `push` (because you want to skip the `push`-triggered jobs).
- If `skip_concurrent_trigger` is not null, then the skipping-rules are changed as follows:
  - Relax the "look only at older runs"-rule
  - Add a new rule: Concurrent skipping is only allowed if the workflow has been triggered by `skip_concurrent_trigger`.

**Comment by fkirc** [comment]
Actually, I am not sure whether this would work, because "looking at younger workflow-runs" implies that those younger workflow-runs might not yet exist.
Remember that we have to make a final skip-decision within a few seconds, so we do not have time to wait until younger workflow-runs are created.
In the end, an experimental implementation could give an answer to this question.

**Comment by icopp** [comment]
For my case, the desired behavior is something like:

- On pull requests, actions run that format/lint, run tests, make review comments on the PR with lint and test results, and push formatted/autofixed code back to the branch
- On non-pull request pushes (on all branches, not just master), actions run that format/lint and push formatted/autofixed code back to the branch

If both run, general git annoyances result from changes being pushed from multiple sources, plus workflow minutes get wasted by the duplicate runs. If the pull request-based trigger doesn't reliably run (since you can't get the pull request info from the push trigger), the automatic review comments don't reliably show up. That last part is where the race condition issue comes in.

**Comment by fkirc** [comment]
I have now implemented the request on the feature-branch `skip_concurrent_trigger`.
However, I would like to have one more real-world-test before I merge this feature.
Therefore, could you test this feature-branch to verify whether this solves the race condition?
You can test the feature-branch with:


```yml
uses: fkirc/skip-duplicate-actions@skip_concurrent_trigger
with:
  github_token: ${{ github.token }}
  skip_concurrent_trigger: 'push'       
```

**Comment by icopp** [comment]
I gave it a try and so far it looks like it's working as expected. The job run from the push trigger happens first (or at least shows up in the list earliest) and cancels when it does the check against the `pre_job`'s result, and the job run from the pull trigger shows up in the list just after that and runs successfully.

My guess here is that GitHub is queuing both jobs runs simultaneously and then they start in order, so that when the check on the push-triggered job happens the pull request-triggered job already exists in the queue.

**Comment by fkirc** [comment]
I agree that this existence-check is rather shady, but it seems that querying "younger workflow-runs" is a viable thing to do.
So would you agree to merge the feature in it's current form?

**Comment by icopp** [comment]
Yes, it looks like it works. I'll let you know if I run into any future trouble with it.

**Comment by fkirc** [comment]
Merged, I hope that this is a reliable fix for the race condition

**Comment by juergba** [comment]
Those double runs for `push` and `pull_request` are a pain in GH actions.
I could not find this `skip_concurrent_trigger` option in your docs, has it been removed meanwhile?

We would need to skip the `push` event whenever the corresponding feature branch is linked to a PR. On the other hand when there is no PR, then run the `push` event on all branches. 

Our coverall steps depend on `pull_request`, so it's the `push` event which has to be skipped.
