### ISSUE TITLE
Error: HttpError: Server Error Error: Server Error

### ISSUE THREAD

**Issue by chiedo** [fkirc/skip-duplicate-actions#45]
👋🏿  firstly, Thanks for this awesome project!

We're using skip-duplicate-actions and every now and then we see this error.

```
Error: HttpError: Server Error
Error: Server Error
```

Do you have any idea what's causing that? It happens quite often.

**Comment by fkirc** [comment]
In 2020, I have seen GitHub service outages that lasted for hours.
Therefore, I would not wonder if GitHub's REST API is rather unstable.

If this is a random failure, then we might workaround with a huge try-catch like this: https://github.com/fkirc/skip-duplicate-actions/pull/46
My point is: If there are random failures, then I want this action to finish with "success" without skipping anything, instead of triggering a failure of an entire workflow.

**Comment by chiedo** [comment]
That try/catch is exactly what I was looking for! Thank you for the quick response.

**Comment by fkirc** [comment]
Merged, thank you for reporting
