### ISSUE TITLE
Make skipping concurrent builds optional

### ISSUE THREAD

**Issue by negz** [fkirc/skip-duplicate-actions#50]
We've found that the ability to skip concurrent builds can be used to workaround required checks on a PR. See https://github.com/crossplane/crossplane/pull/1888 for example. In this instance we:

1. Opened a PR with a commit that would not pass required checks.
1. Updated the commit message and force pushed it.

The CI run from 2 detects the concurrent run from 1 and skips all of our required jobs. GitHub allows us to merge a PR when required tests are skipped, so it would be easy for us to accidentally merge not noting that CI actually did not pass.

I believe ideally in our CI flow this action would skip workflow runs that are identical to previous successful runs, but not skip when an identical concurrent workflow run (which may or may not pass) was detected. Is it possible to add an option to disable skipping concurrent runs?

**Comment by fkirc** [comment]
> We've found that the ability to skip concurrent builds can be used to workaround required checks on a PR. See [crossplane/crossplane#1888](https://github.com/crossplane/crossplane/pull/1888) for example. In this instance we:
> 
> 1. Opened a PR with a commit that would not pass required checks.
> 2. Updated the commit message and force pushed it.
> 
> The CI run from 2 detects the concurrent run from 1 and skips all of our required jobs. GitHub allows us to merge a PR when required tests are skipped, so it would be easy for us to accidentally merge not noting that CI actually did not pass.

I agree that "concurrent skipping" is a dangerous functionality with possibilities of abuse.
In fact, I already fixed a similar vulnerability that relied on multiple branches instead of force-pushes: https://github.com/fkirc/skip-duplicate-actions/pull/36

> I believe ideally in our CI flow this action would skip workflow runs that are identical to previous successful runs, but not skip when an identical concurrent workflow run (which may or may not pass) was detected. Is it possible to add an option to disable skipping concurrent runs?

I see two options to fix this vulnerability:

- Option 1: Check against commit-hashes instead of tree-hashes: This would fix this particular force-push vulnerability, because the commit-hash changes if you change a commit-message.
- Option 2: Add an option to disable concurrent skipping altogether.

I am not sure which option is better.
Concurrent skipping was originally intended for things like "fast tag-pushes" or "pull_request + push"-triggers for the same workflow.

**Comment by negz** [comment]
I think we'd lean toward option 2 in our project. In practice we haven't found concurrent runs to be a significant issue for us historically. We actually adopted this action primarily to skip CI when only markdown files changed, but we do appreciate the ability to not re-run CI when we know based on prior runs that the tree hash will pass CI.

**Comment by fkirc** [comment]
Merged option 2, thank you for reporting

**Comment by negz** [comment]
Thanks for the quick response!
