### ISSUE TITLE
Add option to ignore tree hash for `schedule`/`workflow_dispatch` trigger

### ISSUE THREAD

**Issue by reitermarkus** [fkirc/skip-duplicate-actions#63]
Not sure if this would be useful for other triggers than `schedule`/`workflow_dispatch`.

Basically the use case is the following:

We have a scheduled workflow which *may* run longer than the schedule interval. This workflow does not depend on the repository contents, so the tree hash is irrelevant for determining whether the run is a duplicate. 

If the workflow is already currently running, cancel the current run (`cancel_self: true` akin to `cancel_others`).

Also, I'm not sure if this is the case currently, but in this case, a `schedule` run should also stop a duplicate `workflow_dispatch` from running and vice versa.

**Comment by fkirc** [comment]
Currently, "concurrent skipping" is already possible, but only if the tree hashes are matching.
So I guess that you want a "concurrent skipping" that does not check tree hashes (i.e. always skip if the same workflow is already running concurrently).

So I would merge a PR that adds an additional option like "concurrent_skipping": always | same-content | never.

One more sidenote about "self cancellation":
I would prefer if we stick with the skipping-semantics instead of triggering self-cancellations (unless there is a specific reason why self cancellation is really necessary).

**Comment by fkirc** [comment]
Although I was not originally planning any new features, this was a good opportunity for cleaning existing code.
Therefore, I implemented your request with https://github.com/fkirc/skip-duplicate-actions/pull/66.
I hope that this is sufficient for the goal that you want to achieve, otherwise please let me know if something is broken.

**Comment by reitermarkus** [comment]
Thanks, @fkirc! I will try it out.
